version: '3.9'

services:
  db:
    image: postgres:12.19-alpine
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${QNS_DB_USER}
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "pg_isready -d ${QNS_DB_USER} -U ${QNS_DB_USER}"
        ]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 5s
    networks:
      - quicknotes
    ports:
      - ${QNS_DB_PORT}:${QNS_DB_PORT}

  migrate:
    image: migrate/migrate
    networks:
      - quicknotes
    volumes:
      - ./db/migrations:/migrations
    command:
      [
        "-path",
        "/migrations/",
        "-database",
        "postgres://${QNS_DB_USER}:${POSTGRES_PASSWORD}@db:5432/${QNS_DB_NAME}?sslmode=disable",
        "up"
      ]
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      QNS_DB_USER: ${QNS_DB_USER}
      QNS_DB_NAME: ${QNS_DB_NAME}
    depends_on:
      db:
        condition: service_healthy

  server:
    build:
      context: ./
      dockerfile: dockerfile
    networks:
      - quicknotes
    ports:
      - ${QNS_SERVER_PORT}:${QNS_SERVER_PORT}
    depends_on: [ migrate ]
    environment:
      QNS_DB_USER: ${QNS_DB_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      QNS_DB_NAME: ${QNS_DB_NAME}
      QNS_DB_HOST: ${QNS_DB_HOST}
      QNS_DB_PORT: ${QNS_DB_PORT}
      QNS_SMTP_HOST: ${QNS_SMTP_HOST}
      QNS_SMTP_PORT: ${QNS_SMTP_PORT}
      QNS_SMTP_USER_NAME: ${QNS_SMTP_USER_NAME}
      QNS_SMTP_USER_PASS: ${QNS_SMTP_USER_PASS}
      QNS_SMTP_FROM: ${QNS_SMTP_FROM}

networks:
  quicknotes:
